services:
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - movies:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'example'
volumes:
  movies:
